### ISSUE TITLE
使用https://hub.docker.com/r/xuweijie1015/yapi镜像构建失败：dial tcp 104.18.122.25:443: i/o timeout

### ISSUE THREAD

**Issue by thezhang98** [xwj-vic/yapi#1]
## 版本号
~ 

## 什么问题
~ 提供的docker镜像报：
FATA[0040] failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/9a/9a6684e02573ac76e3a1e21cf9a6e50eb656cb91d2cb185dd689de460efcc7cf/data?verify=1685966521-TXiGJ3ctjaFtL17gWyag9ftoRZA%3D": dial tcp 104.18.122.25:443: i/o timeout

## 如何复现此问题
~ 使用`https://hub.docker.com/r/xuweijie1015/yapi`进行构建

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
 windows

## 更多细节：
设置了全局代理，在windows的cmd可以ping到。

**Comment by xwj-vic** [comment]
docker images 下载不了吗？

**Comment by xwj-vic** [comment]
version: '3'

services:
  yapi-web:
    image: xuweijie1015/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@admin.com
      - YAPI_ADMIN_PASSWORD=admin
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=127.0.0.1
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=true
      - YAPI_MAIL_HOST=xxx
      - YAPI_MAIL_PORT=xxx
      - YAPI_MAIL_FROM=xxx
      - YAPI_MAIL_AUTH_USER=xxx
      - YAPI_MAIL_AUTH_PASS=xxx
      - YAPI_PLUGINS=[{"name":"notifier","options":{"host":"http://localhost:3000"}},{"name":"pl-auto-test","options":{"host":"http://localhost:3000"}},{"name":"interface-oauth2-token"},{"name":"api-watch"}]

    volumes:
      - ../Desktop/data/db:/data/db
    restart: unless-stopped

**Comment by xwj-vic** [comment]
dial tcp 104.18.122.25:443: i/o timeout。是网络问题，可以使用国内的docker代理加速一下

**Comment by thezhang98** [comment]
按理说我开了全局代理，并且cmd也可以正常ping到，不应该出问题。
不过没啥大问题，我看了镜像信息，我这边改了下你的镜像信息自己在本地构建了一个，先试试。
