### ISSUE TITLE
node_modules.zip 不能下载

### ISSUE THREAD

**Issue by Simooonn** [xwj-vic/yapi#12]
## 版本号
~ 

## 什么问题
~
<img width="643" alt="image" src="https://github.com/xwj-vic/yapi/assets/24266163/8ed6345a-df86-474b-a9b3-1332bb29c6fb">

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by xwj-vic** [comment]
这是Git的问题，你需要配置一下能下载大文件

**Comment by Simooonn** [comment]
<img width="628" alt="image" src="https://github.com/xwj-vic/yapi/assets/24266163/61e1b25a-30a8-4793-b740-673617d9b504">

**Comment by Simooonn** [comment]
> 

<img width="628" alt="image" src="https://github.com/xwj-vic/yapi/assets/24266163/ce9e1020-013b-449c-85a7-3eceb489f564">
还是这个问题

**Comment by Simooonn** [comment]
> 这是Git的问题，你需要配置一下能下载大文件
<img width="638" alt="image" src="https://github.com/xwj-vic/yapi/assets/24266163/eb84db0e-0d81-4556-8796-b18ac34135fc">
 还是这个问题
