### ISSUE TITLE
不支持添加分组

### ISSUE THREAD

**Issue by mstaryi** [xwj-vic/yapi#2]
## 版本号
~ 
1.11.0
## 什么问题
~
如果添加分组，界面没有地方可以添加分组
## 如何复现此问题
~ 

## 什么浏览器
~ 
Chrome
## 什么系统（Linux, Windows, macOS）
Linux

**Comment by xwj-vic** [comment]
![image](https://github.com/xwj-vic/yapi/assets/20365749/c8438e5d-a306-4e3f-9a66-084d94aac2fc)

**Comment by xwj-vic** [comment]
这个功能一直都有的
