### ISSUE TITLE
在请求配置中设置Pre-request script，设置脚本为console.log(xxx); 无法在浏览器的console框看到

### ISSUE THREAD

**Issue by thezhang98** [xwj-vic/yapi#3]
## 版本号
~ 

## 什么问题
~ 在请求配置中设置Pre-request script，设置脚本为console.log(xxx); 无法在浏览器的console框看到。原生的项目可以的。
设置 - 请求设置 - Pre-request Script(请求参数处理脚本)，脚本填写如下：
```js
console.log(context.requestBody);
console.log(context.utils);
console.log(context.utils.md5(context.requestBody));
```
## 如何复现此问题
~ 在设置 - 请求设置 - Pre-request Script(请求参数处理脚本)，脚本填写如下：
```js
console.log(context.requestBody);
console.log(context.utils);
console.log(context.utils.md5(context.requestBody));
```
## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Windows

## 更多细节
用原生的项目可以在浏览器的console框看到。现在看不到这个不太利用一些脚本编写~希望作者辛苦看下~

**Comment by thezhang98** [comment]
我发现原因是没有走到请求配置的代码，我先看下代码逻辑

**Comment by xwj-vic** [comment]
的确会出现请求配置脚本无法执行的问题；根因在于源码内无法对"scriptEnable":true的解析；我先修复一下；后续会同步上去

**Comment by thezhang98** [comment]
https://github.com/xwj-vic/yapi/commit/8613dabcb8bbfef87f5a7d2317438226fcbe4ecc
已在本次提交中修复，我关掉这个issue吧
