### ISSUE TITLE
Cannot find module '../../config.json'问题如何解决？

### ISSUE THREAD

**Issue by 2513483494** [xwj-vic/yapi#4]
## 版本号
~ 1.5.0

## 什么问题
~

## 如何复现此问题
~ 按文档方法配置好了环境，但是启动项目就会报错Cannot find module '../../config.json'

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
macos

**Comment by thezhang98** [comment]
注意执行的命令的位置和config.json配置的位置，以下是一个例子：
/data/app
 &nbsp; ┣ config.json  // 注意！！：这里是配置config.json的位置
 &nbsp; ┗ yapi             // 注意！！： 项目位置，一般会把它命名为vendor
&nbsp;  &nbsp; ┣ client 
&nbsp; &nbsp; ┣ common
&nbsp; &nbsp; ┣ docs
&nbsp; &nbsp; ┣ exts
&nbsp; &nbsp; ┣ iconfont
&nbsp; &nbsp; ┣ node_modules
&nbsp; &nbsp; ┣ server
&nbsp; &nbsp; ┣ static
&nbsp; &nbsp; ┣ test
&nbsp; &nbsp; ......

**Comment by 2513483494** [comment]
<img width="1105" alt="截屏2023-06-08 16 19 23" src="https://github.com/xwj-vic/yapi/assets/48058550/243ee97b-4bd5-4b11-9402-55dc30b80135">
下载出来的代码是这种结构，可以看到config的位置明显写的不对，本地开发调试是需要先更改文件目录结构？

**Comment by thezhang98** [comment]
我刚才更新了我的评论，md下空格无效导致了一些理解歧义。
从你现在的配置来看，需要将config.json向上提一级。这个是原项目在[教程](https://hellosean1025.github.io/yapi/devops/index.html)里面明确说出的：
详见其目录配置！

**Comment by 2513483494** [comment]
> 我刚才更新了我的评论，md下空格无效导致了一些理解歧义。 从你现在的配置来看，需要将config.json向上提一级。这个是原项目在[教程](https://hellosean1025.github.io/yapi/devops/index.html)里面明确说出的： 详见其目录配置！

好的 我再好好看看

**Comment by thezhang98** [comment]
![image](https://github.com/xwj-vic/yapi/assets/40171921/092bfdd9-e28d-4c0d-8e5c-a56b93053f20)
原教程的项目配置

**Comment by 2513483494** [comment]
<img width="1230" alt="截屏2023-06-08 16 35 54" src="https://github.com/xwj-vic/yapi/assets/48058550/25cda1de-93dd-4a86-8793-6725a4617c97">
我发现启动项目后无法解析引入的sass文件，导致项目报错，这个是否是因为node-sass的问题呢还是什么问题呢

**Comment by thezhang98** [comment]
新的问题就新开一个issue吧，这个问题如果解决了就关闭吧~

**Comment by 2513483494** [comment]
<img width="1268" alt="截屏2023-06-08 16 40 01" src="https://github.com/xwj-vic/yapi/assets/48058550/92aa4087-bb6d-4985-9b83-9c41e2a74d21">
还有数据库也有报错，我发现把.db删掉后就好了，不晓得是什么情况。。。

**Comment by 2513483494** [comment]
> 新的问题就新开一个issue吧，这个问题如果解决了就关闭吧~

那我新开一个吧
