### ISSUE TITLE
启动报错，似乎是插件问题

### ISSUE THREAD

**Issue by 2513483494** [xwj-vic/yapi#7]
## 版本号
~ 

## 什么问题
~
<img width="535" alt="截屏2023-06-09 09 57 23" src="https://github.com/xwj-vic/yapi/assets/48058550/6d9d6263-7ca0-41c0-878b-7431c6cbc920">

## 如何复现此问题
~ 安装好依赖运行npm run dev
try {
  pluginModuleList = require('./plugin-module.js');
} catch (err) {
  console.log('err', err);
  pluginModuleList = {};
}
错误是这块代码产生的plugin.js

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by xwj-vic** [comment]
有按教程正确安装本地环境吗？我本地重现不了，没有报错
<img width="835" alt="image" src="https://github.com/xwj-vic/yapi/assets/20365749/f0a50d02-f879-416d-b7a2-fc23373cceb0">

**Comment by 2513483494** [comment]
这时候是没有错误的，需要进入项目页面点击swagger导入这个页面就会报错了.





------------------ 原始邮件 ------------------
发件人: XWJ ***@***.***&gt;
发送时间: 2023年6月9日 22:38
收件人: xwj-vic/yapi ***@***.***&gt;
抄送: 2513483494 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xwj-vic/yapi] 启动报错，似乎是插件问题 (Issue #7)





 
有按教程正确安装本地环境吗？我本地重现不了，没有报错

**Comment by xwj-vic** [comment]
按你所说， 项目 -> 数据管理 -> 数据导入 ， 导入swagger json 也没报错

**Comment by 2513483494** [comment]
奇怪了，我就是在这个页面报错，其他页面都没问题，这样的话我后面再看看是否有其他问题吧.





------------------ 原始邮件 ------------------
发件人: XWJ ***@***.***&gt;
发送时间: 2023年6月9日 22:43
收件人: xwj-vic/yapi ***@***.***&gt;
抄送: 2513483494 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xwj-vic/yapi] 启动报错，似乎是插件问题 (Issue #7)





 
按你所说， 项目 -&gt; 数据管理 -&gt; 数据导入 ， 导入swagger json 也没报错

**Comment by xwj-vic** [comment]
好的，有兴趣的话，欢迎提代码共同维护

**Comment by 2513483494** [comment]
好的 感谢回复





------------------ 原始邮件 ------------------
发件人: XWJ ***@***.***&gt;
发送时间: 2023年6月9日 22:50
收件人: xwj-vic/yapi ***@***.***&gt;
抄送: 2513483494 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xwj-vic/yapi] 启动报错，似乎是插件问题 (Issue #7)





 
好的，有兴趣的话，欢迎提代码共同维护
