### ISSUE TITLE
官网下载的按照文档所说在http://127.0.0.1:3000/project/20/data地址就会报错是为什么呢？

### ISSUE THREAD

**Issue by 2513483494** [xwj-vic/yapi#9]
## 版本号
~ 

## 什么问题
~官网下载的yapi按照文档所说在http://127.0.0.1:3000/project/20/data地址就会报错是为什么呢？直接白屏，对比了下代码，没找到是修复了什么地方

## 如何复现此问题
~ 

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
mac

**Comment by xwj-vic** [comment]
可以再描述一遍你的问题吗？是哪一步报错？贴一下错误信息？
